# Generated by Django 4.0.4 on 2022-05-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portifolio',
            new_name='Portfolio',
        ),
    ]
