# Generated by Django 4.0.4 on 2022-05-21 06:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=160)),
                ('atividade_CI', models.IntegerField(blank=True, null=True)),
                ('atividade_Rai', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Ambiente', models.CharField(max_length=128)),
                ('area_Ambiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finalidade', models.CharField(choices=[('Armazenamento', 'Armazenamento'), ('Fabrico', 'Fabrico/Manuentenção')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=160)),
                ('fabrico_CI', models.IntegerField(blank=True, null=True)),
                ('fabrico_Rai', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('armazem_CI', models.IntegerField(blank=True, null=True)),
                ('armazem_Rai', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=9)),
                ('describe', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('criated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('referencia', models.IntegerField()),
                ('describ', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[(1, '1ª'), (2, '2ª'), (3, '3ª'), (4, '4ª')], max_length=25)),
                ('plus', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateField(auto_now=True)),
                ('utilization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.utilizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Estabelecimento', models.CharField(max_length=160)),
                ('morada_Estabelecimento', models.CharField(max_length=160)),
                ('postalCode', models.CharField(max_length=7, null=True)),
                ('numero_Fiscal', models.CharField(max_length=9)),
                ('responsavel_legal', models.CharField(max_length=148)),
                ('data_Funcionamento', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=9, null=True)),
                ('delegado_seguranca', models.CharField(max_length=160)),
                ('elemento_seguranca', models.CharField(max_length=160)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ar_Livre', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=3, null=True)),
                ('area_Bruta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('arquitetura_disponivel', models.IntegerField(choices=[(1, 'Possui em formato compatível com CAD'), (2, 'Possui em outro formato digital ou analógico não compatível com CAD'), (3, 'Não possui')], null=True)),
                ('armazenExclusiv', models.BooleanField(default=False, null=True)),
                ('atividade', models.CharField(max_length=160)),
                ('carga_Incendio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('efetivo_Local_D', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('efetivo_Local_E', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('efetivo_Total', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('local_Risco_D', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=3, null=True)),
                ('local_Risco_E', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=3, null=True)),
                ('subsolo', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('orcamento_Data', models.DateField(auto_now_add=True, null=True)),
                ('utilizacao_Tipo', models.IntegerField(choices=[(1, 'Habitacionais'), (2, 'Estacionamentos'), (3, 'Administrativos'), (4, 'Escolares'), (5, 'Hospitalares e Lares de Idosos'), (6, 'Espectáculos e Reuniões Públicas'), (7, 'Hoteleiros e Restauração'), (8, 'Comerciais e Gares de Transportes'), (9, 'Desportivos e de Lazer'), (10, 'Museus e Galerias de Arte'), (11, 'Biblioteca de Arquivos'), (12, 'Industriais, Oficinas, e Armazéns')], null=True)),
                ('categoria', models.IntegerField(choices=[(1, '1ª'), (2, '2ª'), (3, '3ª'), (4, '4ª')], null=True)),
                ('fatorEspecial', models.BooleanField(default=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('criated_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('im_aware_it', models.BooleanField(default=False)),
                ('concelho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.concelho')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.statusorder')),
            ],
        ),
        migrations.CreateModel(
            name='LocalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.locale')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.material')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.atividade')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauenPublic.locale')),
            ],
        ),
    ]
