# Generated by Django 4.0.4 on 2022-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauenPublic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='utilization',
            field=models.IntegerField(choices=[(1, 'Habitacionais'), (2, 'Estacionamentos'), (3, 'Administrativos'), (4, 'Escolares'), (5, 'Hospitalares e Lares de Idosos'), (6, 'Espectáculos e Reuniões Públicas'), (7, 'Hoteleiros e Restauração'), (8, 'Comerciais e Gares de Transportes'), (9, 'Desportivos e de Lazer'), (10, 'Museus e Galerias de Arte'), (11, 'Biblioteca de Arquivos'), (12, 'Industriais, Oficinas, e Armazéns')], null=True),
        ),
    ]
